server.port=8080
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.datasource.url=jdbc:mysql://localhost:3306/webbansach
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=22130145@st.hcmuaf.edu.vn
spring.mail.password=zhzrmngkxhoetdpn

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Database Configuration (MySQL + Laragon)
spring.datasource.url=jdbc:mysql://localhost:3306/webbansach?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Email SMTP Configuration (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=22130003@st.hcmuaf.edu.vn
spring.mail.password=nktbpuidrzclnwmv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
main
