server.port=8082
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Database Configuration (MySQL + Laragon)
spring.datasource.url=jdbc:mysql://localhost:3306/webbansach?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Email SMTP Configuration (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=22130003@st.hcmuaf.edu.vn
spring.mail.password=nktbpuidrzclnwmv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# VNPay Configuration (Sandbox defaults)
vnpay.tmnCode=70YD6OFI
vnpay.hashSecret=YER68F0DEMFL1S306DLCLTEY2NSVNAMK
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:8082/api/payment/vnpay-callback
